### ISSUE TITLE
Can you help?

### ISSUE THREAD

**Issue by Denisov21** [talmand/Brackets-HTML-Templates#26]
![immagine 1 26062015](https://cloud.githubusercontent.com/assets/2547815/8387885/a1ac7032-1c5c-11e5-926a-6da93bc7f1d6.png)

I would like to ask you if you had an idea to solve two warnings

**Comment by talmand** [comment]
I don't believe those are warnings, just general information as to what the validator is doing behind the scenes.

**Comment by Denisov21** [comment]
Ok, thank you!
