### ISSUE TITLE
Custom template?

### ISSUE THREAD

**Issue by arsistyle** [talmand/Brackets-HTML-Templates#30]
How create a custom template?

**Comment by talmand** [comment]
Look in the html folder for the templates. Create your template and drop the html file in there.

Update modal.html in the html folder to indicate your new template. This is the modal you see when selecting a template in Brackets.

Update main.js to point to your new template. This makes the selection in the modal work.

**Comment by arsistyle** [comment]
@talmand what´s the name of the folder of templates? is "htmlContent" located in C:\Users...\AppData\Roaming\Brackets\extensions\user\dvuyka.templates(Win)?

**Comment by talmand** [comment]
Crap, sorry, totally missed on following up on this.

The templates are in the html folder included with the extension, which will be stored wherever the extension is saved on your machine. Will likely will be somewhere around the location you mentioned.
